- name: Playbook
  hosts: all
  debugger: on_failed
  gather_facts: false

  tasks:
    - name: Wait until the instance is ready
      ansible.builtin.wait_for_connection:

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Podman present
      become: true
      ansible.builtin.dnf:
        name: podman
        update_cache: true
        state: present

    - name: Run consumer container
      containers.podman.podman_container:
        name: consumer
        image: ghcr.io/platform-engineering-org/poc:main
        detach: true
        state: started
        recreate: true
        env:
          SECRET_NAME: "poc"
          REGION: "{{ AWS_REGION }}"
